# Generated by Django 5.2.7 on 2026-03-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_worker_age_worker_passport_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
