# Generated by Django 5.2.7 on 2026-03-04 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_worker_telegram_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Ariza', 'verbose_name_plural': 'Arizalar'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': 'Ish', 'verbose_name_plural': 'Ishlar'},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name': "Botdan o'tgan user", 'verbose_name_plural': "Botdan o'tgan userlar"},
        ),
    ]
