# Generated by Django 5.2.7 on 2026-03-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_application_options_alter_job_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='client_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
