# Generated by Django 5.2.7 on 2026-03-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_client_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='required_workers',
            field=models.IntegerField(default=1),
        ),
    ]
