# Generated by Django 5.2.7 on 2026-03-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_location_url_job_required_workers'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='client_tg_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
