# Generated by Django 5.2.7 on 2026-03-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_job_client_tg_username_alter_job_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
