# Generated by Django 6.0.3 on 2026-03-05 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_application_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='location_photo',
            field=models.ImageField(blank=True, null=True, upload_to='location_photos/'),
        ),
    ]
